services:
  byparr:
    image: ghcr.io/thephaseless/byparr
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ./screenshots:/app/screenshots # For screenshots when exception occurs
    ports:
      - "8191:8191"
