services:
  byparr:
    image: ghcr.io/thephaseless/byparr
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=INFO
      - MAX_CHROME_LIFETIME=300
    ports:
      - "8191:8191"
